package student;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import static student.DBconnection.con;

public class Home extends javax.swing.JFrame {
    
    int xx, xy;
    DefaultTableModel studentTbl;
    DefaultTableModel courseTbl;
    public Home() {
        initComponents();
        switchPanels(pnlHome);
        
        // Button visual effects
        JButton [] btns = {BtnSearch, BtnRefresh, BtnAdd, BtnUpdate, BtnDelete, jButton7, btnPrintStudent, btnHome, btnDash, btnStudent, btnLogout, btnCourse, 
            btnAddCourse, btnDeleteCourse, btnUpdateCourse, btnClearCourse, btnPrintCourse, btnRefreshCourse, btnSearchCourse, BtnSearchStudentCourse};
        for (JButton btn: btns){
            btn.setBackground(new Color (51,51,51));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e){
                }
                @Override
                public void mousePressed(MouseEvent e){  
                    btn.setBackground(new Color(36, 49, 138));
                }
                @Override
                public void mouseReleased(MouseEvent e){  
                    btn.setBackground(new Color(54, 81, 207));
                }
                @Override
                public void mouseEntered(MouseEvent e){
                    btn.setBackground(new Color(54, 81, 207));
                }
                @Override
                public void mouseExited(MouseEvent e){
                    btn.setBackground(new Color (51,51,51));
                }
            });
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnDash = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnCourse = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlCTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        pnlCCenter = new javax.swing.JLayeredPane();
        pnlHome = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlStudent = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        studentIdField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        genderCBox = new javax.swing.JComboBox<>();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cityField = new javax.swing.JComboBox<>();
        BtnAdd = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        addressNoStreetField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        BtnRefresh = new javax.swing.JButton();
        BtnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        btnPrintStudent = new javax.swing.JButton();
        pnlCourse = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        fieldCourseId = new javax.swing.JTextField();
        fieldStudentId = new javax.swing.JTextField();
        cLabel3 = new javax.swing.JLabel();
        cLabel1 = new javax.swing.JLabel();
        cLabel2 = new javax.swing.JLabel();
        cLabel4 = new javax.swing.JLabel();
        cLabel6 = new javax.swing.JLabel();
        cLabel5 = new javax.swing.JLabel();
        cLabel7 = new javax.swing.JLabel();
        cboxModule1 = new javax.swing.JComboBox<>();
        cboxModule2 = new javax.swing.JComboBox<>();
        cboxModule3 = new javax.swing.JComboBox<>();
        cboxModule4 = new javax.swing.JComboBox<>();
        cboxModule5 = new javax.swing.JComboBox<>();
        pnlLeftTop = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        fieldStudentCourse = new javax.swing.JTextField();
        BtnSearchStudentCourse = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        SearchField1 = new javax.swing.JTextField();
        btnRefreshCourse = new javax.swing.JButton();
        btnSearchCourse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        btnAddCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnUpdateCourse = new javax.swing.JButton();
        btnClearCourse = new javax.swing.JButton();
        btnPrintCourse = new javax.swing.JButton();
        pnlCBottom = new javax.swing.JPanel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlRoot.setBackground(new java.awt.Color(204, 204, 204));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(21, 25, 28));
        pnlSide.setPreferredSize(new java.awt.Dimension(90, 750));

        jPanel5.setBackground(new java.awt.Color(21, 25, 28));
        jPanel5.setPreferredSize(new java.awt.Dimension(90, 125));

        btnDash.setBackground(new java.awt.Color(34, 40, 44));
        btnDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-dashboard-layout-24.png"))); // NOI18N
        btnDash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSide.add(jPanel5);

        btnHome.setBackground(new java.awt.Color(34, 40, 44));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-25.png"))); // NOI18N
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setPreferredSize(new java.awt.Dimension(50, 50));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlSide.add(btnHome);

        btnStudent.setBackground(new java.awt.Color(34, 40, 44));
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-25.png"))); // NOI18N
        btnStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStudent.setPreferredSize(new java.awt.Dimension(50, 50));
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        pnlSide.add(btnStudent);

        btnCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-reserve-24.png"))); // NOI18N
        btnCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCourse.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });
        pnlSide.add(btnCourse);

        btnLogout.setBackground(new java.awt.Color(34, 40, 44));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-24.png"))); // NOI18N
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setPreferredSize(new java.awt.Dimension(50, 50));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlSide.add(btnLogout);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(204, 204, 204));
        pnlCenter.setPreferredSize(new java.awt.Dimension(1306, 762));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlCTop.setBackground(new java.awt.Color(34, 40, 44));
        pnlCTop.setPreferredSize(new java.awt.Dimension(1306, 70));
        pnlCTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlCTopMouseDragged(evt);
            }
        });
        pnlCTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCTopMousePressed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Roboto Thin", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("DASHBOARD");

        javax.swing.GroupLayout pnlCTopLayout = new javax.swing.GroupLayout(pnlCTop);
        pnlCTop.setLayout(pnlCTopLayout);
        pnlCTopLayout.setHorizontalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1024, Short.MAX_VALUE))
        );
        pnlCTopLayout.setVerticalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlCTop, java.awt.BorderLayout.PAGE_START);

        pnlCCenter.setMaximumSize(new java.awt.Dimension(1306, 640));

        pnlHome.setBackground(new java.awt.Color(153, 153, 153));
        pnlHome.setPreferredSize(new java.awt.Dimension(1306, 652));

        jPanel8.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel8.setPreferredSize(new java.awt.Dimension(752, 70));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("kisharacosta74@gmail.com");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 58)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Student Management System ");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-student-male-100.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("CODSE241F-073");
        jLabel15.setPreferredSize(new java.awt.Dimension(359, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Developed By: Kishara Hasaranga");
        jLabel16.setPreferredSize(new java.awt.Dimension(359, 30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(194, 194, 194))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(181, 181, 181)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1307, Short.MAX_VALUE)
            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pnlStudent.setBackground(new java.awt.Color(102, 102, 102));
        pnlStudent.setPreferredSize(new java.awt.Dimension(1306, 652));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 25, 28), 1, true));

        studentIdField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        genderCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Attack Helicopter", "Waterproof Sandwitch" }));
        genderCBox.setBorder(null);

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        phoneField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        dobField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Date of Birth");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Student Id");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Student Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Phone No.");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Address City");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Address No. & Street");

        cityField.setEditable(true);
        cityField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cityField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City", "Panadura", " " }));
        cityField.setBorder(null);

        BtnAdd.setBackground(new java.awt.Color(34, 40, 44));
        BtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        BtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd.setText("Add");
        BtnAdd.setBorder(null);
        BtnAdd.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(34, 40, 44));
        BtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Delete");
        BtnDelete.setBorder(null);
        BtnDelete.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnUpdate.setBackground(new java.awt.Color(34, 40, 44));
        BtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.setBorder(null);
        BtnUpdate.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(34, 40, 44));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Clear");
        jButton7.setBorder(null);
        jButton7.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        addressNoStreetField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(genderCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(addressNoStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addressNoStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 25, 28), 1, true));

        jPanel4.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel4.setPreferredSize(new java.awt.Dimension(752, 70));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Search Student");

        SearchField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        BtnRefresh.setBackground(new java.awt.Color(34, 40, 44));
        BtnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        BtnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        BtnRefresh.setText("Refresh");
        BtnRefresh.setBorder(null);
        BtnRefresh.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });

        BtnSearch.setBackground(new java.awt.Color(34, 40, 44));
        BtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        BtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearch.setText("Search");
        BtnSearch.setBorder(null);
        BtnSearch.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "std_Id", "Name", "Dob", "Gender", "Email", "PhoneNo", "Address", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);
        if (studentTable.getColumnModel().getColumnCount() > 0) {
            studentTable.getColumnModel().getColumn(7).setHeaderValue("City");
        }

        btnPrintStudent.setBackground(new java.awt.Color(34, 40, 44));
        btnPrintStudent.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnPrintStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintStudent.setText("Print");
        btnPrintStudent.setBorder(null);
        btnPrintStudent.setPreferredSize(new java.awt.Dimension(100, 30));
        btnPrintStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrintStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout pnlStudentLayout = new javax.swing.GroupLayout(pnlStudent);
        pnlStudent.setLayout(pnlStudentLayout);
        pnlStudentLayout.setHorizontalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStudentLayout.setVerticalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlCourse.setBackground(new java.awt.Color(51, 51, 51));
        pnlCourse.setPreferredSize(new java.awt.Dimension(1306, 652));

        pnlLeft.setBackground(new java.awt.Color(204, 204, 204));
        pnlLeft.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 25, 28), 1, true));

        fieldCourseId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        fieldStudentId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        cLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cLabel3.setForeground(new java.awt.Color(0, 0, 0));
        cLabel3.setText("Module 1");

        cLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cLabel1.setForeground(new java.awt.Color(0, 0, 0));
        cLabel1.setText("Id");

        cLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cLabel2.setForeground(new java.awt.Color(0, 0, 0));
        cLabel2.setText("Student's Id");

        cLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cLabel4.setForeground(new java.awt.Color(0, 0, 0));
        cLabel4.setText("Module 2");

        cLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cLabel6.setForeground(new java.awt.Color(0, 0, 0));
        cLabel6.setText("Module 4");

        cLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cLabel5.setForeground(new java.awt.Color(0, 0, 0));
        cLabel5.setText("Module 3");

        cLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cLabel7.setForeground(new java.awt.Color(0, 0, 0));
        cLabel7.setText("Module 5");

        cboxModule1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxModule1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Introduction to Programming", "Data Structures", "Algorithms ", "Object-Oriented Programming (OOP)", "Functional Programming", "Programming Paradigms" }));
        cboxModule1.setBorder(null);

        cboxModule2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxModule2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Version Control", "Software Design and Architecture", "Testing and Debugging" }));
        cboxModule2.setBorder(null);

        cboxModule3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxModule3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frontend Development", "Backend Development", "APIs and Web Services", "Full Stack Development" }));
        cboxModule3.setBorder(null);

        cboxModule4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxModule4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android Development", "iOS Development", "Cross-Platform Development" }));
        cboxModule4.setBorder(null);

        cboxModule5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxModule5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Database Management", "Data Science and Machine Learning", "Data Visualization", "Operating Systems" }));
        cboxModule5.setBorder(null);

        pnlLeftTop.setBackground(java.awt.SystemColor.controlHighlight);
        pnlLeftTop.setPreferredSize(new java.awt.Dimension(508, 70));

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Student's ID");

        fieldStudentCourse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        BtnSearchStudentCourse.setBackground(new java.awt.Color(34, 40, 44));
        BtnSearchStudentCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        BtnSearchStudentCourse.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearchStudentCourse.setText("Search");
        BtnSearchStudentCourse.setBorder(null);
        BtnSearchStudentCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSearchStudentCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchStudentCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftTopLayout = new javax.swing.GroupLayout(pnlLeftTop);
        pnlLeftTop.setLayout(pnlLeftTopLayout);
        pnlLeftTopLayout.setHorizontalGroup(
            pnlLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftTopLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(fieldStudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(BtnSearchStudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlLeftTopLayout.setVerticalGroup(
            pnlLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftTopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fieldStudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearchStudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLeftTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldStudentId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCourseId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxModule1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxModule2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxModule3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxModule4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxModule5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLeftTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel3)
                    .addComponent(cboxModule1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxModule2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel5)
                    .addComponent(cboxModule3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel6)
                    .addComponent(cboxModule4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel7)
                    .addComponent(cboxModule5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRight.setBackground(new java.awt.Color(204, 204, 204));
        pnlRight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 25, 28), 1, true));

        jPanel7.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel7.setPreferredSize(new java.awt.Dimension(752, 70));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Search Course");

        SearchField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnRefreshCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnRefreshCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnRefreshCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshCourse.setText("Refresh");
        btnRefreshCourse.setBorder(null);
        btnRefreshCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRefreshCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCourseActionPerformed(evt);
            }
        });

        btnSearchCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnSearchCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnSearchCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCourse.setText("Search");
        btnSearchCourse.setBorder(null);
        btnSearchCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(SearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnRefreshCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(SearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "StudentId", "Module1", "Module2", "Module3", "Module4", "Module5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCourse);

        btnAddCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnAddCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setText("Add");
        btnAddCourse.setBorder(null);
        btnAddCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnDeleteCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnDeleteCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCourse.setText("Delete");
        btnDeleteCourse.setBorder(null);
        btnDeleteCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnUpdateCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnUpdateCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnUpdateCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCourse.setText("Update");
        btnUpdateCourse.setBorder(null);
        btnUpdateCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUpdateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCourseActionPerformed(evt);
            }
        });

        btnClearCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnClearCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnClearCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnClearCourse.setText("Clear");
        btnClearCourse.setBorder(null);
        btnClearCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        btnClearCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCourseActionPerformed(evt);
            }
        });

        btnPrintCourse.setBackground(new java.awt.Color(34, 40, 44));
        btnPrintCourse.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnPrintCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintCourse.setText("Print");
        btnPrintCourse.setBorder(null);
        btnPrintCourse.setPreferredSize(new java.awt.Dimension(100, 30));
        btnPrintCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrintCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrintCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlCourseLayout = new javax.swing.GroupLayout(pnlCourse);
        pnlCourse.setLayout(pnlCourseLayout);
        pnlCourseLayout.setHorizontalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCourseLayout.setVerticalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlCCenter.setLayer(pnlHome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCCenter.setLayer(pnlStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCCenter.setLayer(pnlCourse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlCCenterLayout = new javax.swing.GroupLayout(pnlCCenter);
        pnlCCenter.setLayout(pnlCCenterLayout);
        pnlCCenterLayout.setHorizontalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, 1307, 1307, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCCenterLayout.createSequentialGroup()
                    .addComponent(pnlCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        pnlCCenterLayout.setVerticalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlCenter.add(pnlCCenter, java.awt.BorderLayout.CENTER);

        pnlCBottom.setBackground(new java.awt.Color(34, 40, 44));
        pnlCBottom.setPreferredSize(new java.awt.Dimension(1306, 40));

        javax.swing.GroupLayout pnlCBottomLayout = new javax.swing.GroupLayout(pnlCBottom);
        pnlCBottom.setLayout(pnlCBottomLayout);
        pnlCBottomLayout.setHorizontalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        pnlCBottomLayout.setVerticalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCBottom, java.awt.BorderLayout.PAGE_END);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //panelButtonStudent
    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        switchPanels(pnlStudent);
        jLabelTitle.setText("Student Registration");
        // Student auto load data to table
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         //Connection con = DBconnection.getConnection();
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nibm","root","");
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("select * from student");
         
         
         while(rs.next()){
          String std_Id = rs.getString("studentId");
          String Name = rs.getString("studentName");
          String Dob = rs.getString("studentDob");
          String Gender = rs.getString("studentGender");
          String Email = rs.getString("studentEmail");
          String PhoneNo = rs.getString("studentContact");
          String Address = rs.getString("addressNoStreet");
          String City = rs.getString("addressCity");
          
          Object[] obj = {std_Id,Name,Dob,Gender,Email,PhoneNo,Address,City};
          studentTbl =(DefaultTableModel) studentTable.getModel();
          studentTbl.addRow(obj);
        }
         
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnStudentActionPerformed
    
    //panelButtonHome
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        switchPanels(pnlHome);
        jLabelTitle.setText("DASHBOARD");
    }//GEN-LAST:event_btnHomeActionPerformed
    //panelButtonLogout
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int exit = JOptionPane.showConfirmDialog(this, "Are you sure you want to Log Out?", "Log Out", JOptionPane.YES_NO_OPTION);
        if(exit == 0){
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    //drag window- mouse dragged
    private void pnlCTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xx , y- xy);
    }//GEN-LAST:event_pnlCTopMouseDragged
    //drag window- mouse pressed
    private void pnlCTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlCTopMousePressed
    //Insert Student
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        String studentId = studentIdField.getText();
        String studentName = nameField.getText();
        String dob = dobField.getText();
        String gender = (String) genderCBox.getSelectedItem();
        String email = emailField.getText();
        String contact = phoneField.getText();
        String Street_No = addressNoStreetField.getText();
        String City = (String) cityField.getSelectedItem();
        
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nibm","root","");
         Connection con = DBconnection.getConnection();
          PreparedStatement pst = con.prepareStatement("insert into student(studentId ,studentName ,studentDob ,studentGender ,studentEmail ,studentContact ,addressNoStreet, addressCity) values (?,?,?,?,?,?,?,?)");
          
          pst.setString(1,studentId);
          pst.setString(2,studentName);
          pst.setString(3, dob);
          pst.setString(4, gender);
          pst.setString(5, email);
          pst.setString(6, contact);
          pst.setString(7,Street_No);
          pst.setString(8, City);
          
          int rowCount = pst.executeUpdate();
          if(rowCount > 0){
              JOptionPane.showMessageDialog(this,"Saved successfully");
          } else{
              JOptionPane.showMessageDialog(this,"Error! Please try again");
          }
          con.close();
          
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BtnAddActionPerformed
    //Update Student
    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        String studentId = studentIdField.getText();
        String studentName = nameField.getText();
        String dob = dobField.getText();
        String gender = (String) genderCBox.getSelectedItem();
        String email = emailField.getText();
        String contact = phoneField.getText();
        String Street_No = addressNoStreetField.getText();
        String City = (String) cityField.getSelectedItem();
        
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DBconnection.getConnection();
          PreparedStatement pst = con.prepareStatement("update student set studentName=?, studentDob=?, studentGender=?, studentEmail=?, studentContact=?, addressNoStreet=?, addressCity=?  where studentId=?");
          
          pst.setString(1,studentName);
          pst.setString(2, dob);
          pst.setString(3, gender);
          pst.setString(4, email);
          pst.setString(5, contact);
          pst.setString(6,Street_No);
          pst.setString(7, City);
          pst.setString(8,studentId);

          int rowCount = pst.executeUpdate();
          if(rowCount > 0){
              JOptionPane.showMessageDialog(this,"Update successfull!");
          } 
          else {
              JOptionPane.showMessageDialog(this,"Error! Please try again");
          }
          con.close();
          
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed
    
    //Delete Student
    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        String studentId = studentIdField.getText();
        
        try{
            Connection con = DBconnection.getConnection();
            String sql = "delete from student  where studentId=?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, studentId);
            
            int rowCount = pst.executeUpdate();
            if(rowCount > 0){
              JOptionPane.showMessageDialog(this,"Delete successfull!");
            } 
            else{
              JOptionPane.showMessageDialog(this,"Error! Please try again");
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed
    //Clear Student
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        studentIdField.setText("");
        nameField.setText("");
        dobField.setText("");
        genderCBox.setSelectedIndex(0);
        emailField.setText("");
        phoneField.setText("");
        addressNoStreetField.setText("");
        cityField.setSelectedIndex(0);
    }//GEN-LAST:event_jButton7ActionPerformed
    
    //Search Student
    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
       String studentId = SearchField.getText();         
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DBconnection.getConnection();
            PreparedStatement ptstmt = con.prepareStatement("select * from student where studentId=?");
            ptstmt.setString(1,studentId);
            ResultSet rs = ptstmt.executeQuery();
            
            studentTbl = (DefaultTableModel) studentTable.getModel();
            studentTbl.setRowCount(0); // Clear the table
            while (rs.next()) {
                Object[] row = {
                    rs.getString("studentId"),
                    rs.getString("studentName"),
                    rs.getString("studentDob"),
                    rs.getString("studentGender"),
                    rs.getString("studentEmail"),  
                    rs.getString("studentContact"),
                    rs.getString("addressNoStreet"),
                    rs.getString("addressCity")
                };
                studentTbl.addRow(row);
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unexpected Error Occurred: " + e.getMessage());
        } 
    }//GEN-LAST:event_BtnSearchActionPerformed
    //Refresh Student
    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DBconnection.getConnection();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("select * from student");
         
         studentTbl.setRowCount(0); //clear table
         while(rs.next()){
          String std_Id = rs.getString("studentId");
          String Name = rs.getString("studentName");
          String Dob = rs.getString("studentDob");
          String Gender = rs.getString("studentGender");
          String Email = rs.getString("studentEmail");
          String PhoneNo = rs.getString("studentContact");
          String Address = rs.getString("addressNoStreet");
          String City = rs.getString("addressCity");
          
          Object[] obj = {std_Id,Name,Dob,Gender,Email,PhoneNo,Address,City};
          studentTbl =(DefaultTableModel) studentTable.getModel();
          studentTbl.addRow(obj);
        }
        con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BtnRefreshActionPerformed
    //panelButtonCourse
    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        switchPanels(pnlCourse);
        jLabelTitle.setText("Student Course");
        //auto load
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DBconnection.getConnection();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("select * from course");
         
         while(rs.next()){
          String Id = rs.getString("id");
          String StudentId = rs.getString("stId");
          String module1=  rs.getString("module1");
          String module2 = rs.getString("module2");
          String module3 = rs.getString("module3");
          String module4 = rs.getString("module4");
          String module5 = rs.getString("module5");
          
          Object[] obj = {Id,StudentId,module1,module2,module3,module4,module5};
          studentTbl =(DefaultTableModel) tableCourse.getModel();
          studentTbl.addRow(obj);
        }
        con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnCourseActionPerformed
    //Insert Course
    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        String courseId = fieldCourseId.getText();
        String studentId = fieldStudentId.getText();
        String module1 = (String) cboxModule1.getSelectedItem();
        String module2 = (String) cboxModule2.getSelectedItem();
        String module3 = (String) cboxModule3.getSelectedItem();
        String module4 = (String) cboxModule4.getSelectedItem();
        String module5 = (String) cboxModule5.getSelectedItem();
        
        try{
          Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con = DBconnection.getConnection();
          PreparedStatement pst = con.prepareStatement("insert into course(id  ,stId  ,module1 ,module2 ,module3 ,module4 ,module5) values (?,?,?,?,?,?,?)");
          
          pst.setString(1,courseId);
          pst.setString(2,studentId);
          pst.setString(3, module1);
          pst.setString(4, module2);
          pst.setString(5, module3);
          pst.setString(6, module4);
          pst.setString(7,module5);
          
          int rowCount = pst.executeUpdate();
          if(rowCount > 0){
              JOptionPane.showMessageDialog(this,"Saved successfully");
          } else{
              JOptionPane.showMessageDialog(this,"Error! Please try again");
          }
          con.close();
          
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAddCourseActionPerformed
    
    //Delete Course
    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        String courseId = fieldCourseId.getText();
        
        try{
            Connection con = DBconnection.getConnection();
            String sql = "delete from course  where id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, courseId);
            
            int rowCount = pst.executeUpdate();
            if(rowCount > 0){
              JOptionPane.showMessageDialog(this,"Delete successfull!");
            } 
            else{
              JOptionPane.showMessageDialog(this,"Error! Please try again");
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteCourseActionPerformed
    //Update Course
    private void btnUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCourseActionPerformed
        String courseId = fieldCourseId.getText();
        String studentId = fieldStudentId.getText();
        String module1 = (String) cboxModule1.getSelectedItem();
        String module2 = (String) cboxModule2.getSelectedItem();
        String module3 = (String) cboxModule3.getSelectedItem();
        String module4 = (String) cboxModule4.getSelectedItem();
        String module5 = (String) cboxModule5.getSelectedItem();
        
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DBconnection.getConnection();
          PreparedStatement pst = con.prepareStatement("update course set stId=?, module1=?, module2=?, module3=?, module4=?, module5=? where id=?");
               
          pst.setString(1,studentId);
          pst.setString(2, module1);
          pst.setString(3, module2);
          pst.setString(4, module3);
          pst.setString(5, module4);
          pst.setString(6,module5);
          pst.setString(7,courseId);

          int rowCount = pst.executeUpdate();
          if(rowCount > 0){
              JOptionPane.showMessageDialog(this,"Update successfull!");
          } 
          else {
              JOptionPane.showMessageDialog(this,"Error! Please try again");
          }
          con.close();
          
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateCourseActionPerformed
    //Clear Course
    private void btnClearCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCourseActionPerformed
        fieldCourseId.setText("");
        fieldStudentId.setText("");
        cboxModule1.setSelectedIndex(0);
        cboxModule2.setSelectedIndex(0);
        cboxModule3.setSelectedIndex(0);
        cboxModule4.setSelectedIndex(0);
        cboxModule5.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearCourseActionPerformed
    // Refresh Course
    private void btnRefreshCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCourseActionPerformed
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DBconnection.getConnection();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("select * from course");
         
         courseTbl.setRowCount(0); //clear table
         while(rs.next()){
          String Id = rs.getString("id");
          String StudentId = rs.getString("stId");
          String module1=  rs.getString("module1");
          String module2 = rs.getString("module2");
          String module3 = rs.getString("module3");
          String module4 = rs.getString("module4");
          String module5 = rs.getString("module5");
          
          Object[] obj = {Id,StudentId,module1,module2,module3,module4,module5};
          courseTbl =(DefaultTableModel) tableCourse.getModel();
          courseTbl.addRow(obj);
        }
        con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnRefreshCourseActionPerformed
    
    //Search Course
    private void btnSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCourseActionPerformed
        String courseID = fieldCourseId.getText();         
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DBconnection.getConnection();
            
            PreparedStatement ps = con.prepareStatement("select * from course where id=?");
            ps.setString(1,courseID);
            
            ResultSet rs = ps.executeQuery();
            
            courseTbl = (DefaultTableModel) tableCourse.getModel();
            courseTbl.setRowCount(0); // Clear the table
            while (rs.next()) {
                Object[] row = {
                    rs.getString("id"),
                    rs.getString("stId"),
                    rs.getString("module1"),
                    rs.getString("module2"),
                    rs.getString("module3"),
                    rs.getString("module4"),
                    rs.getString("module5")
                };
                courseTbl.addRow(row);
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unexpected Error Occurred: " + e.getMessage());
        } 
    }//GEN-LAST:event_btnSearchCourseActionPerformed
    //Search StudentCourse
    private void BtnSearchStudentCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchStudentCourseActionPerformed
        String studentId = fieldStudentCourse.getText();         
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DBconnection.getConnection();
            PreparedStatement ptstmt = con.prepareStatement("select * from course where stId=?");
            ptstmt.setString(1,studentId);
            ResultSet rs = ptstmt.executeQuery();
              
            while (rs.next()) {
                fieldCourseId.setText(rs.getString("id"));
                fieldStudentId.setText(rs.getString("stId"));
                cboxModule1.setSelectedItem(rs.getString("module1"));
                cboxModule2.setSelectedItem(rs.getString("module2"));
                cboxModule3.setSelectedItem(rs.getString("module3"));
                cboxModule4.setSelectedItem(rs.getString("module4"));
                cboxModule5.setSelectedItem(rs.getString("module5"));
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unexpected Error Occurred: " + e.getMessage());
        } 
    }//GEN-LAST:event_BtnSearchStudentCourseActionPerformed
    //Print Jasper (Student and Course Details)
    private void btnPrintCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCourseActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nibm","root","");
            String reportPath = "C:\\Users\\kisha\\JaspersoftWorkspace\\MyReports\\StudentCourseReport.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null,con);
            JasperViewer .viewReport(jp);
        
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Unexpected Error Occurred: " + e.getMessage());
       }
    }//GEN-LAST:event_btnPrintCourseActionPerformed
    //Print Jasper (StudentDetails)
    private void btnPrintStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintStudentActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nibm","root","");
            String reportPath = "C:\\Users\\kisha\\JaspersoftWorkspace\\MyReports\\StudentReport.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null,con);
            JasperViewer .viewReport(jp);
        
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Unexpected Error Occurred: " + e.getMessage());
       }
    }//GEN-LAST:event_btnPrintStudentActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Switch panels
    public void switchPanels(JPanel panel){
        pnlCCenter.removeAll();
        pnlCCenter.add(panel);
        pnlCCenter.repaint();
        pnlCCenter.revalidate();
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JButton BtnSearchStudentCourse;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField SearchField1;
    private javax.swing.JTextField addressNoStreetField;
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnClearCourse;
    private javax.swing.JButton btnCourse;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrintCourse;
    private javax.swing.JButton btnPrintStudent;
    private javax.swing.JButton btnRefreshCourse;
    private javax.swing.JButton btnSearchCourse;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnUpdateCourse;
    private javax.swing.JLabel cLabel1;
    private javax.swing.JLabel cLabel2;
    private javax.swing.JLabel cLabel3;
    private javax.swing.JLabel cLabel4;
    private javax.swing.JLabel cLabel5;
    private javax.swing.JLabel cLabel6;
    private javax.swing.JLabel cLabel7;
    private javax.swing.JComboBox<String> cboxModule1;
    private javax.swing.JComboBox<String> cboxModule2;
    private javax.swing.JComboBox<String> cboxModule3;
    private javax.swing.JComboBox<String> cboxModule4;
    private javax.swing.JComboBox<String> cboxModule5;
    private javax.swing.JComboBox<String> cityField;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fieldCourseId;
    private javax.swing.JTextField fieldStudentCourse;
    private javax.swing.JTextField fieldStudentId;
    private javax.swing.JComboBox<String> genderCBox;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JPanel pnlCBottom;
    private javax.swing.JLayeredPane pnlCCenter;
    private javax.swing.JPanel pnlCTop;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlCourse;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlLeftTop;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JTable studentTable;
    private javax.swing.JTable tableCourse;
    // End of variables declaration//GEN-END:variables
}
